//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemeeee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerTc { get; set; }
        public string CustomerStudentNumber { get; set; }
        public string CustomerAge { get; set; }
        public string CustomerMail { get; set; }
        public string CustomerFaculty { get; set; }
        public string CustomerDepartment { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string CustomerCinsiyet { get; set; }
        public string CustomerEvent { get; set; }
    }
}
