//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemeeee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int EventId { get; set; }
        public string EventName { get; set; }
        public string Free { get; set; }
        public string UnitPrice { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Faculty { get; set; }
        public string Department { get; set; }
        public string Date { get; set; }
        public string Information { get; set; }
        public string Image { get; set; }
    }
}
